### ISSUE TITLE
crashed when input is specified

### ISSUE THREAD

**Issue by 1iu** [RBReif/bgp-hijack-detection#1]
The error is as follows:

```
Found update File 20230724.0000
      -->will be inserted: true
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12a260b]

goroutine 1 [running]:
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:74
main.updateOriginCounter(0x341e, 0x1, 0x1)
	/Users/xxx/bgp-hijack-detection/ASsummary.go:40 +0x4b
main.updateSummary({{0xc1654581e0, 0x17, 0x20}, {{{0xc1800604d0, 0x4, 0x4}, {0xc1800604ac, 0x4, 0x4}}, {0xc1654581c0, ...}, ...}, ...})
	/Users/xxx/bgp-hijack-detection/ASsummary.go:125 +0x137
main.insertAndFindConflicts({{{0xc1800604d0, 0x4, 0x4}, {0xc1800604ac, 0x4, 0x4}}, {0xc1654581c0, 0x17, 0x20}, 0x341e, ...}, ...)
	/Users/xxx/bgp-hijack-detection/PrefixTrie.go:230 +0x69b
main.(*BGPDump).parseUpdatesAndInsert(0x13c1240?, {0xc165104a20?, 0xc0002c7d40?}, 0x60?)
	/Users/xxx/bgp-hijack-detection/Routeviews.go:219 +0x9c5
main.processBGPFiles()
	/Users/xxx/bgp-hijack-detection/Main.go:234 +0xc51
main.main()
	/Users/xxx/bgp-hijack-detection/Main.go:285 +0x52f
```
The possible reason is that `mutex` in ASSummary.go was not properly initialized when `inputDirectory` is specified.

**Comment by RBReif** [comment]
@1iu fixed the issue. Problem was that `mutex` was only initialized, if `liveMode` was set to true.
